Update the executor image from Container Linux to Fedora CoreOS

diff --git a/buildman/qemu-coreos/Dockerfile b/buildman/qemu-coreos/Dockerfile
--- a/buildman/qemu-coreos/Dockerfile
+++ b/buildman/qemu-coreos/Dockerfile
@@ -1,23 +1,31 @@
-FROM debian
+FROM debian:latest as executor-img
+ARG location
+ARG channel
+ARG version
 
-RUN apt-get clean && apt-get update && apt-get upgrade -y # 03APR2017
+RUN [ -z "${location}" ] || [ -z "${channel}" ] || [ -z "${version}" ] && echo "ARG location, channel, version are required" && exit 1 || true
+RUN apt-get clean && apt-get update && apt-get upgrade -y
 RUN apt-get install -y \
-  bzip2 \
-  curl \
+  xz-utils \
+  curl
+
+RUN echo "Downloading" ${location}
+RUN curl -s -o coreos_production_qemu_image.qcow2.xz ${location} && unxz coreos_production_qemu_image.qcow2.xz
+
+
+FROM debian:latest
+ARG location
+ARG channel
+ARG version
+
+RUN apt-get clean && apt-get update && apt-get upgrade -y && \
+  apt-get install -y \
   openssh-client \
-  qemu-kvm
-
-ARG channel=stable
-ARG version=current
-
-RUN echo "Downloading http://${channel}.release.core-os.net/amd64-usr/${version}/coreos_production_qemu_image.img.bz2"
-RUN curl -s -O http://${channel}.release.core-os.net/amd64-usr/${version}/coreos_production_qemu_image.img.bz2 && \
-  bzip2 -d coreos_production_qemu_image.img.bz2
-
-RUN apt-get remove -y curl bzip2 && \
+  qemu-kvm && \
   apt-get clean && \
   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
+COPY --from=executor-img /coreos_production_qemu_image.qcow2 /coreos_production_qemu_image.qcow2
 COPY start.sh /start.sh
 
 LABEL com.coreos.channel ${channel}
